spring.application.name=hello
spring.datasource.url=jdbc:mariadb://localhost:3306/recensement
spring.datasource.username=root
spring.datasource.password=${abc}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=fr.diginamic.hello.config.LegacyMariaDBDialect
spring.jpa.show-sql=true
application.init=false